import Foundation

enum L10n {
    static let languageKey = "ui.language"
    static let supportedLanguages = ["system", "en", "de", "fr", "pt", "nl", "es"]
    static let languageNames = ["system":"Systemsprache", "en":"English", "de":"Deutsch", "fr":"Français", "pt":"Português", "nl":"Nederlands", "es":"Español"]
    private static let values: [String: [String: String]] = [
        "title": ["de":"Nextcloud Apple Photos Connector", "en":"Nextcloud Apple Photos Connector", "nl":"Nextcloud Apple Photos Connector", "es":"Nextcloud Apple Photos Connector", "fr":"Nextcloud Apple Photos Connector", "pt":"Nextcloud Apple Photos Connector"],
        "subtitle": ["de":"Überträgt deine Fotos, Videos und Alben aus Apple Fotos sicher in deine Nextcloud. Zusätzlich zu dieser App wird die zugehörige App auf dem Nextcloud-Server benötigt.", "en":"Safely transfers your photos, videos, and albums from Apple Photos to your Nextcloud. The corresponding app on the Nextcloud server is also required.", "nl":"Draagt je foto's, video's en albums veilig over van Apple Foto's naar je Nextcloud. De bijbehorende app op de Nextcloud-server is ook vereist.", "es":"Transfiere de forma segura tus fotos, vídeos y álbumes de Apple Fotos a tu Nextcloud. También se necesita la aplicación correspondiente en el servidor Nextcloud.", "fr":"Transfère en toute sécurité vos photos, vidéos et albums d’Apple Photos vers votre Nextcloud. L’application correspondante sur le serveur Nextcloud est également requise.", "pt":"Transfere com segurança as suas fotografias, vídeos e álbuns do Apple Photos para a sua Nextcloud. Também é necessária a aplicação correspondente no servidor Nextcloud."],
        "settings": ["de":"Einstellungen öffnen …", "en":"Open Settings …", "nl":"Instellingen openen …", "es":"Abrir ajustes …", "fr":"Ouvrir les réglages …"],
        "importStatus": ["de":"Importstatus", "en":"Import status", "nl":"Importstatus", "es":"Estado de importación", "fr":"État de l’importation"],
        "requestPhotoAccess": ["de":"Zugriff auf Apple Photos anfordern", "en":"Request Apple Photos Access", "nl":"Toegang tot Apple Photos aanvragen", "es":"Solicitar acceso a Apple Photos", "fr":"Demander l’accès à Apple Photos", "pt":"Solicitar acesso ao Apple Photos"],
        "upload": ["de":"Fotos & Alben übernehmen", "en":"Import Photos & Albums", "fr":"Importer photos et albums", "pt":"Importar fotos e álbuns", "nl":"Foto's en albums overnemen", "es":"Importar fotos y álbumes"],
        "photos": ["de":"Fotos", "en":"Photos", "fr":"Photos", "pt":"Fotos", "nl":"Foto's", "es":"Fotos"],
        "albums": ["de":"Alben", "en":"Albums", "fr":"Albums", "pt":"Álbuns", "nl":"Albums", "es":"Álbumes"],
        "selectAll": ["de":"Alle auswählen", "en":"Select all", "fr":"Tout sélectionner", "pt":"Selecionar tudo", "nl":"Alles selecteren", "es":"Seleccionar todo"],
        "clearSelection": ["de":"Auswahl aufheben", "en":"Clear selection", "fr":"Effacer la sélection", "pt":"Limpar seleção", "nl":"Selectie wissen", "es":"Borrar selección"],
        "albumSync": ["de":"Alben abgleichen", "en":"Sync albums", "fr":"Synchroniser les albums", "pt":"Sincronizar álbuns", "nl":"Albums synchroniseren", "es":"Sincronizar álbumes"],
        "language": ["de":"Sprache", "en":"Language", "fr":"Langue", "pt":"Idioma", "nl":"Taal", "es":"Idioma"],
        "systemLanguage": ["de":"Systemsprache", "en":"System language", "fr":"Langue du système", "pt":"Idioma do sistema", "nl":"Systeemtaal", "es":"Idioma del sistema"],
        "uploadRunning": ["de":"Upload läuft …", "en":"Upload in progress …", "fr":"Téléversement en cours…", "pt":"Carregamento em curso…", "nl":"Upload loopt …", "es":"Subida en curso …"],
        "uploadComplete": ["de":"Upload abgeschlossen", "en":"Upload complete", "fr":"Téléversement terminé", "pt":"Carregamento concluído", "nl":"Upload voltooid", "es":"Subida completada"],
        "albumSyncComplete": ["de":"Album-Abgleich abgeschlossen", "en":"Album sync complete", "fr":"Synchronisation des albums terminée", "pt":"Sincronização de álbuns concluída", "nl":"Albumsynchronisatie voltooid", "es":"Sincronización de álbumes completada"],
        "noPhotos": ["de":"Keine Fotos in der sichtbaren Mediathek gefunden.", "en":"No photos found in the visible library.", "fr":"Aucune photo trouvée dans la photothèque visible.", "pt":"Nenhuma foto encontrada na fototeca visível.", "nl":"Geen foto's gevonden in de zichtbare bibliotheek.", "es":"No se encontraron fotos en la fototeca visible."],
        "selectedPhotos": ["de":"Fotos ausgewählt", "en":"photos selected", "fr":"photos sélectionnées", "pt":"fotos selecionadas", "nl":"foto's geselecteerd", "es":"fotos seleccionadas"],
        "connection": ["de":"Nextcloud-Verbindung", "en":"Nextcloud connection", "fr":"Connexion Nextcloud", "pt":"Ligação Nextcloud", "nl":"Nextcloud-verbinding", "es":"Conexión de Nextcloud"],
        "checkConnection": ["de":"Verbindung prüfen", "en":"Check connection", "fr":"Vérifier la connexion", "pt":"Verificar ligação", "nl":"Verbinding controleren", "es":"Comprobar conexión"],
        "loginFlowConnect": ["de":"Mit Nextcloud verbinden", "en":"Connect to Nextcloud", "fr":"Se connecter à Nextcloud", "pt":"Ligar ao Nextcloud", "nl":"Verbinden met Nextcloud", "es":"Conectarse a Nextcloud"],
        "loginFlowBrowserOpened": ["de":"Browser wird geöffnet …", "en":"Opening browser …", "fr":"Ouverture du navigateur…", "pt":"A abrir o navegador…", "nl":"Browser wordt geopend …", "es":"Abriendo el navegador …"],
        "loginFlowWaiting": ["de":"Warte auf Anmeldung in Nextcloud …", "en":"Waiting for Nextcloud sign-in …", "fr":"En attente de la connexion à Nextcloud…", "pt":"A aguardar o início de sessão no Nextcloud…", "nl":"Wachten op aanmelding bij Nextcloud …", "es":"Esperando el inicio de sesión en Nextcloud …"],
        "loginFlowCancel": ["de":"Anmeldung abbrechen", "en":"Cancel sign-in", "fr":"Annuler la connexion", "pt":"Cancelar início de sessão", "nl":"Aanmelding annuleren", "es":"Cancelar inicio de sesión"],
        "loginFlowCancelled": ["de":"Anmeldung abgebrochen", "en":"Sign-in cancelled", "fr":"Connexion annulée", "pt":"Início de sessão cancelado", "nl":"Aanmelding geannuleerd", "es":"Inicio de sesión cancelado"],
        "loginFlowConnected": ["de":"✓ Mit Nextcloud verbunden", "en":"✓ Connected to Nextcloud", "fr":"✓ Connecté à Nextcloud", "pt":"✓ Ligado ao Nextcloud", "nl":"✓ Verbonden met Nextcloud", "es":"✓ Conectado a Nextcloud"],
        "loginFlowFailed": ["de":"Die Anmeldung bei Nextcloud ist fehlgeschlagen.", "en":"Nextcloud sign-in failed.", "fr":"La connexion à Nextcloud a échoué.", "pt":"O início de sessão no Nextcloud falhou.", "nl":"Aanmelden bij Nextcloud mislukt.", "es":"El inicio de sesión en Nextcloud ha fallado."],
        "connectAnotherAccount": ["de":"Mit anderem Konto verbinden", "en":"Connect with another account", "fr":"Se connecter avec un autre compte", "pt":"Ligar com outra conta", "nl":"Verbinden met een ander account", "es":"Conectar con otra cuenta"],
        "disconnect": ["de":"Verbindung trennen", "en":"Disconnect", "fr":"Déconnecter", "pt":"Desligar", "nl":"Verbinding verbreken", "es":"Desconectar"],
        "disconnectConfirmationTitle": ["de":"Verbindung zu Nextcloud trennen?", "en":"Disconnect from Nextcloud?", "fr":"Se déconnecter de Nextcloud ?", "pt":"Desligar do Nextcloud?", "nl":"Verbinding met Nextcloud verbreken?", "es":"¿Desconectar de Nextcloud?"],
        "disconnectConfirmationMessage": ["de":"Die gespeicherten Zugangsdaten werden von diesem Mac entfernt. Bereits übertragene Fotos, Videos und Alben in Nextcloud bleiben unverändert.", "en":"The saved credentials will be removed from this Mac. Photos, videos, and albums already transferred to Nextcloud will remain unchanged.", "fr":"Les identifiants enregistrés seront supprimés de ce Mac. Les photos, vidéos et albums déjà transférés vers Nextcloud resteront inchangés.", "pt":"As credenciais guardadas serão removidas deste Mac. As fotos, vídeos e álbuns já transferidos para o Nextcloud permanecerão inalterados.", "nl":"De opgeslagen inloggegevens worden van deze Mac verwijderd. Foto's, video's en albums die al naar Nextcloud zijn overgedragen, blijven ongewijzigd.", "es":"Las credenciales guardadas se eliminarán de este Mac. Las fotos, los vídeos y los álbumes ya transferidos a Nextcloud permanecerán sin cambios."],
        "target": ["de":"Zielverzeichnis", "en":"Target directory", "fr":"Répertoire cible", "pt":"Diretório de destino", "nl":"Doelmap", "es":"Directorio de destino"],
        "chooseTarget": ["de":"Zielverzeichnis auswählen …", "en":"Choose target directory …", "fr":"Choisir le répertoire cible…", "pt":"Escolher diretório de destino…", "nl":"Doelmap kiezen …", "es":"Elegir directorio de destino …"],
        "changeTarget": ["de":"Zielverzeichnis ändern", "en":"Change target directory", "fr":"Modifier le répertoire cible", "pt":"Alterar diretório de destino", "nl":"Doelmap wijzigen", "es":"Cambiar directorio de destino"],
        "changeTargetConfirmationTitle": ["de":"Zielverzeichnis ändern?", "en":"Change destination folder?", "fr":"Modifier le dossier de destination ?", "pt":"Alterar a pasta de destino?", "nl":"Doelmap wijzigen?", "es":"¿Cambiar la carpeta de destino?"],
        "changeTargetConfirmationMessage": ["de":"Das neue Zielverzeichnis wird für künftig importierte Fotos und Videos verwendet. Bereits übertragene Medien bleiben an ihrem bisherigen Speicherort und werden nicht erneut übertragen.", "en":"The new destination folder will be used for photos and videos imported in the future. Previously transferred media will remain in their current location and will not be transferred again.", "fr":"Le nouveau dossier de destination sera utilisé pour les photos et vidéos importées à l’avenir. Les médias déjà transférés resteront à leur emplacement actuel et ne seront pas transférés à nouveau.", "pt":"A nova pasta de destino será utilizada para fotos e vídeos importados no futuro. Os conteúdos multimédia já transferidos permanecerão na localização atual e não serão transferidos novamente.", "nl":"De nieuwe doelmap wordt gebruikt voor foto's en video's die in de toekomst worden geïmporteerd. Eerder overgedragen media blijven op hun huidige locatie en worden niet opnieuw overgedragen.", "es":"La nueva carpeta de destino se utilizará para las fotos y los vídeos que se importen en el futuro. Los archivos multimedia ya transferidos permanecerán en su ubicación actual y no se volverán a transferir."],
        "changeTargetConfirm": ["de":"Zielverzeichnis ändern", "en":"Change destination folder", "fr":"Modifier le dossier de destination", "pt":"Alterar a pasta de destino", "nl":"Doelmap wijzigen", "es":"Cambiar la carpeta de destino"],
        "behavior": ["de":"Verhalten", "en":"Behavior", "fr":"Comportement", "pt":"Comportamento", "nl":"Gedrag", "es":"Comportamiento"],
        "configuredUser": ["de":"Benutzer", "en":"User", "fr":"Utilisateur", "pt":"Utilizador", "nl":"Gebruiker", "es":"Usuario"],
        "noUserConfigured": ["de":"Kein Benutzer konfiguriert", "en":"No user configured", "fr":"Aucun utilisateur configuré", "pt":"Nenhum utilizador configurado", "nl":"Geen gebruiker geconfigureerd", "es":"Ningún usuario configurado"],
        "noServerConfigured": ["de":"Kein Server konfiguriert", "en":"No server configured", "fr":"Aucun serveur configuré", "pt":"Nenhum servidor configurado", "nl":"Geen server geconfigureerd", "es":"Ningún servidor configurado"],
        "retryTransfer": ["de":"Medien nach Löschung auf dem Server erneut übertragen", "en":"Retransfer media deleted on the server", "fr":"Retransférer les médias supprimés du serveur", "pt":"Transferir novamente mídias excluídas do servidor", "nl":"Media die op de server zijn verwijderd opnieuw overzetten", "es":"Volver a transferir medios eliminados del servidor"],
        "debugMode": ["de":"Debug-Modus", "en":"Debug mode", "fr":"Mode débogage", "pt":"Modo de depuração", "nl":"Debugmodus", "es":"Modo de depuración"],
        "selectAlbums": ["de":"Alben auswählen", "en":"Select albums", "fr":"Sélectionner des albums", "pt":"Selecionar álbuns", "nl":"Albums selecteren", "es":"Seleccionar álbumes"],
        "apply": ["de":"Übernehmen", "en":"Apply", "fr":"Appliquer", "pt":"Aplicar", "nl":"Toepassen", "es":"Aplicar"],
        "cancel": ["de":"Abbrechen", "en":"Cancel", "fr":"Annuler", "pt":"Cancelar", "nl":"Annuleren", "es":"Cancelar"],
        "selected": ["de":"Ausgewählt", "en":"Selected", "fr":"Sélectionné", "pt":"Selecionado", "nl":"Geselecteerd", "es":"Seleccionado"],
        "newFolder": ["de":"Neuer Unterordner …", "en":"New subfolder …", "fr":"Nouveau sous-dossier…", "pt":"Nova subpasta…", "nl":"Nieuwe submap …", "es":"Nueva subcarpeta …"],
        "choose": ["de":"Auswählen", "en":"Choose", "fr":"Choisir", "pt":"Escolher", "nl":"Kiezen", "es":"Elegir"],
        "create": ["de":"Anlegen", "en":"Create", "fr":"Créer", "pt":"Criar", "nl":"Maken", "es":"Crear"]
        ,"targetNotSelected": ["de":"Nicht ausgewählt", "en":"Not selected", "fr":"Non sélectionné", "pt":"Não selecionado", "nl":"Niet geselecteerd", "es":"No seleccionado"]
        ,"albumsSelected": ["de":"Alben ausgewählt", "en":"albums selected", "fr":"albums sélectionnés", "pt":"álbuns selecionados", "nl":"albums geselecteerd", "es":"álbumes seleccionados"]
        ,"uploadTarget": ["de":"Upload-Ziel", "en":"Upload target", "fr":"Cible de téléversement", "pt":"Destino do carregamento", "nl":"Uploaddoel", "es":"Destino de subida"]
        ,"uploadProgress": ["de":"Upload-Fortschritt", "en":"Upload progress", "fr":"Progression du téléversement", "pt":"Progresso do carregamento", "nl":"Uploadvoortgang", "es":"Progreso de subida"]
        ,"file": ["de":"Datei", "en":"File", "fr":"Fichier", "pt":"Ficheiro", "nl":"Bestand", "es":"Archivo"]
        ,"failed": ["de":"Fehlgeschlagen", "en":"Failed", "fr":"Échec", "pt":"Falhou", "nl":"Mislukt", "es":"Fallido"]
        ,"noNewUploads": ["de":"Keine neuen Uploads", "en":"No new uploads", "fr":"Aucun nouveau téléversement", "pt":"Nenhum carregamento novo", "nl":"Geen nieuwe uploads", "es":"No hay nuevas subidas"]
        ,"preparingUploads": ["de":"Uploads werden vorbereitet …", "en":"Preparing uploads …", "fr":"Préparation des téléversements…", "pt":"A preparar carregamentos…", "nl":"Uploads voorbereiden …", "es":"Preparando subidas …"]
        ,"transferred": ["de":"übertragen", "en":"transferred", "fr":"transférées", "pt":"transferidas", "nl":"overgedragen", "es":"transferidas"]
        ,"albumSyncGroup": ["de":"Album-Abgleich", "en":"Album sync", "fr":"Synchronisation des albums", "pt":"Sincronização de álbuns", "nl":"Albumsynchronisatie", "es":"Sincronización de álbumes"]
        ,"membershipsToCheck": ["de":"Zu prüfende Album-Mitgliedschaften", "en":"Album memberships to check", "fr":"Appartenances d’albums à vérifier", "pt":"Associações de álbuns a verificar", "nl":"Te controleren albumm lidmaatschappen", "es":"Membresías de álbumes a comprobar"]
        ,"membershipsNotice": ["de":"Zu prüfende Album-Mitgliedschaften: %d (%@)", "en":"Album memberships to check: %d (%@)", "fr":"Appartenances d’albums à vérifier : %d (%@)", "pt":"Associações de álbuns a verificar: %d (%@)", "nl":"Te controleren albumm lidmaatschappen: %d (%@)", "es":"Membresías de álbumes a comprobar: %d (%@)"]
        ,"notDeletedNotice": ["de":"Bestehende Dateien, Alben und Zuordnungen werden nicht gelöscht.", "en":"Existing files, albums, and mappings are not deleted.", "fr":"Les fichiers, albums et associations existants ne sont pas supprimés.", "pt":"Ficheiros, álbuns e associações existentes não são eliminados.", "nl":"Bestaande bestanden, albums en koppelingen worden niet verwijderd.", "es":"Los archivos, álbumes y asociaciones existentes no se eliminan."]
        ,"albumsChecking": ["de":"Alben werden geprüft …", "en":"Checking albums …", "fr":"Vérification des albums…", "pt":"A verificar álbuns…", "nl":"Albums controleren …", "es":"Comprobando álbumes …"]
        ,"debug": ["de":"Debug", "en":"Debug", "fr":"Débogage", "pt":"Depuração", "nl":"Debug", "es":"Depuración"]
        ,"noNetworkActivity": ["de":"Noch keine Netzwerkaktivität protokolliert.", "en":"No network activity logged yet.", "fr":"Aucune activité réseau enregistrée.", "pt":"Ainda não há atividade de rede registada.", "nl":"Nog geen netwerkactiviteit gelogd.", "es":"Aún no hay actividad de red registrada."]
        ,"cancelUpload": ["de":"Abbrechen", "en":"Cancel", "fr":"Annuler", "pt":"Cancelar", "nl":"Annuleren", "es":"Cancelar"]
        ,"photosAccessRestricted": ["de":"Der Fotozugriff ist eingeschränkt.", "en":"Photo access is limited.", "fr":"L’accès aux photos est limité.", "pt":"O acesso às fotografias é limitado.", "nl":"Toegang tot foto's is beperkt.", "es":"El acceso a las fotos es limitado."]
        ,"photoAccessDenied": ["de":"Bitte erlaube den Zugriff auf Apple Photos in den Systemeinstellungen.", "en":"Allow Apple Photos access in System Settings.", "fr":"Autorisez l’accès à Apple Photos dans les réglages système.", "pt":"Permita o acesso ao Apple Photos nos Ajustes do Sistema.", "nl":"Sta toegang tot Apple Photos toe in Systeeminstellingen.", "es":"Permite el acceso a Apple Photos en Ajustes del Sistema."]
        ,"requestPhotos": ["de":"Fotozugriff prüfen und Fotos einlesen …", "en":"Check photo access and load photos …", "fr":"Vérifier l’accès et charger les photos…", "pt":"Verificar acesso e carregar fotografias…", "nl":"Fototoegang controleren en foto's laden …", "es":"Comprobar acceso y cargar fotos …"]
        ,"uploadingOriginals": ["de":"Originale werden hochgeladen", "en":"Uploading originals", "fr":"Téléversement des originaux", "pt":"A carregar originais", "nl":"Originelen uploaden", "es":"Subiendo originales"]
        ,"view": ["de":"Ansicht", "en":"View", "fr":"Affichage", "pt":"Vista", "nl":"Weergave", "es":"Vista"]
        ,"server": ["de":"Server", "en":"Server", "fr":"Serveur", "pt":"Servidor", "nl":"Server", "es":"Servidor"]
        ,"username": ["de":"Benutzername", "en":"Username", "fr":"Nom d’utilisateur", "pt":"Nome de utilizador", "nl":"Gebruikersnaam", "es":"Nombre de usuario"]
        ,"password": ["de":"App-Passwort", "en":"App password", "fr":"Mot de passe d’application", "pt":"Palavra-passe da app", "nl":"App-wachtwoord", "es":"Contraseña de la app"]
        ,"import": ["de":"Importieren", "en":"Import", "fr":"Importer", "pt":"Importar", "nl":"Importeren", "es":"Importar"]
        ,"languageSection": ["de":"Sprache / Language", "en":"Language", "fr":"Langue", "pt":"Idioma", "nl":"Taal", "es":"Idioma"]
        ,"folderName": ["de":"Name des Ordners", "en":"Folder name", "fr":"Nom du dossier", "pt":"Nome da pasta", "nl":"Mapnaam", "es":"Nombre de carpeta"]
        ,"selectedPrefix": ["de":"Ausgewählt", "en":"Selected", "fr":"Sélectionné", "pt":"Selecionado", "nl":"Geselecteerd", "es":"Seleccionado"]
        ,"folderWillBeCreatedUnder": ["de":"Der Ordner wird unter %@ angelegt.", "en":"The folder will be created under %@.", "fr":"Le dossier sera créé sous %@.", "pt":"A pasta será criada em %@.", "nl":"De map wordt aangemaakt onder %@.", "es":"La carpeta se creará bajo %@."]
        ,"uploadsProgressFormat": ["de":"%d von %d Uploads", "en":"%d of %d uploads", "fr":"%d sur %d téléversements", "pt":"%d de %d carregamentos", "nl":"%d van %d uploads", "es":"%d de %d subidas"]
        ,"photoCountOne": ["de":"Foto", "en":"photo", "fr":"photo", "pt":"foto", "nl":"foto", "es":"foto"]
        ,"photoCountMany": ["de":"Fotos", "en":"photos", "fr":"photos", "pt":"fotos", "nl":"foto's", "es":"fotos"]
        ,"videoCountOne": ["de":"Video", "en":"video", "fr":"vidéo", "pt":"vídeo", "nl":"video", "es":"vídeo"]
        ,"videoCountMany": ["de":"Videos", "en":"videos", "fr":"vidéos", "pt":"vídeos", "nl":"video's", "es":"vídeos"]
        ,"transferredCount": ["de":"%d %@ übertragen", "en":"%d %@ transferred", "fr":"%d %@ transféré(s)", "pt":"%d %@ transferido(s)", "nl":"%d %@ overgedragen", "es":"%d %@ transferido(s)"]
        ,"alreadyInCloudCount": ["de":"%d %@ bereits in der Cloud", "en":"%d %@ already in the cloud", "fr":"%d %@ déjà dans le cloud", "pt":"%d %@ já na nuvem", "nl":"%d %@ al in de cloud", "es":"%d %@ ya está en la nube"]
        ,"albumOne": ["de":"Album abgeglichen", "en":"album checked", "fr":"album vérifié", "pt":"álbum verificado", "nl":"album gecontroleerd", "es":"álbum comprobado"]
        ,"albumMany": ["de":"Alben abgeglichen", "en":"albums checked", "fr":"albums vérifiés", "pt":"álbuns verificados", "nl":"albums gecontroleerd", "es":"álbumes comprobados"]
        ,"albumSyncResult": ["de":"Album-Abgleich abgeschlossen · %d %@", "en":"Album sync complete · %d %@", "fr":"Synchronisation terminée · %d %@", "pt":"Sincronização concluída · %d %@", "nl":"Albumsynchronisatie voltooid · %d %@", "es":"Sincronización completada · %d %@"]
        ,"media": ["de":"Medien", "en":"media", "fr":"médias", "pt":"mídia", "nl":"media", "es":"medios"]
        ,"notChecked": ["de":"Verbindung nicht geprüft", "en":"Connection not checked", "fr":"Connexion non vérifiée", "pt":"Ligação não verificada", "nl":"Verbinding niet gecontroleerd", "es":"Conexión no comprobada"]
        ,"connectionSuccess": ["de":"✓ Verbindung erfolgreich", "en":"✓ Connection successful", "fr":"✓ Connexion réussie", "pt":"✓ Ligação bem-sucedida", "nl":"✓ Verbinding geslaagd", "es":"✓ Conexión correcta"]
        ,"authError": ["de":"Benutzername oder Passwort sind nicht korrekt.", "en":"Username or password is incorrect.", "fr":"Nom d’utilisateur ou mot de passe incorrect.", "pt":"O nome de utilizador ou a palavra-passe está incorreto.", "nl":"Gebruikersnaam of wachtwoord is onjuist.", "es":"El nombre de usuario o la contraseña no son correctos."]
        ,"appMissing": ["de":"Nextcloud APC ist auf diesem Nextcloud-Server nicht installiert oder nicht aktiviert.", "en":"Nextcloud APC is not installed or enabled on this Nextcloud server.", "fr":"Nextcloud APC n’est pas installé ou activé sur ce serveur.", "pt":"O Nextcloud APC não está instalado ou ativado neste servidor.", "nl":"Nextcloud APC is niet geïnstalleerd of geactiveerd op deze server.", "es":"Nextcloud APC no está instalado o activado en este servidor."]
        ,"serverUnavailable": ["de":"Der Nextcloud-Server ist nicht erreichbar.", "en":"The Nextcloud server is unreachable.", "fr":"Le serveur Nextcloud est inaccessible.", "pt":"O servidor Nextcloud não está acessível.", "nl":"De Nextcloud-server is niet bereikbaar.", "es":"No se puede acceder al servidor Nextcloud."]
        ,"unexpectedResponse": ["de":"Unerwartete Serverantwort", "en":"Unexpected server response", "fr":"Réponse inattendue du serveur", "pt":"Resposta inesperada do servidor", "nl":"Onverwachte serverrespons", "es":"Respuesta inesperada del servidor"]
        ,"targetNotFound": ["de":"Zielverzeichnis nicht gefunden.", "en":"Target directory not found.", "fr":"Répertoire cible introuvable.", "pt":"Diretório de destino não encontrado.", "nl":"Doelmap niet gevonden.", "es":"No se encontró el directorio de destino."]
        ,"targetCheckFailed": ["de":"Zielverzeichnis konnte nicht geprüft werden.", "en":"Target directory could not be checked.", "fr":"Impossible de vérifier le répertoire cible.", "pt":"Não foi possível verificar o diretório de destino.", "nl":"Doelmap kon niet worden gecontroleerd.", "es":"No se pudo comprobar el directorio de destino."]
        ,"invalidFolderName": ["de":"Ungültiger Ordnername.", "en":"Invalid folder name.", "fr":"Nom de dossier invalide.", "pt":"Nome de pasta inválido.", "nl":"Ongeldige mapnaam.", "es":"Nombre de carpeta no válido."]
        ,"folderCreateFailed": ["de":"Ordner konnte nicht angelegt werden.", "en":"Folder could not be created.", "fr":"Impossible de créer le dossier.", "pt":"Não foi possível criar a pasta.", "nl":"Map kon niet worden gemaakt.", "es":"No se pudo crear la carpeta."]
    ]
    static func currentLanguage(defaults: UserDefaults? = nil) -> String {
        let defaults = defaults ?? (UserDefaults(suiteName: "de.applephotosconnector.macagent") ?? .standard)
        let stored = defaults.string(forKey: languageKey)
        let selected = supportedLanguages.contains(stored ?? "") ? stored! : "system"
        return selected == "system" ? (Locale.current.language.languageCode?.identifier ?? "en") : selected
    }
    static func count(_ number: Int, singularKey: String, pluralKey: String? = nil, language: String? = nil) -> String {
        let key = number == 1 ? singularKey : (pluralKey ?? singularKey)
        return "\(number) \(text(key, language: language))"
    }
    static func text(_ key: String, language: String? = nil) -> String { values[key]?[language ?? currentLanguage()] ?? values[key]?["en"] ?? key }
    static func format(_ key: String, _ args: CVarArg..., language: String? = nil) -> String {
        String(format: text(key, language: language), arguments: args)
    }
}
