<?php
declare(strict_types=1);
namespace OCA\ApplePhotosConnector\Controller;
use OCA\ApplePhotosConnector\AppInfo\Application; use OCA\ApplePhotosConnector\Service\AlbumSyncOrchestrator; use OCP\AppFramework\Controller; use OCP\AppFramework\Http\Attribute\NoAdminRequired; use OCP\AppFramework\Http\Attribute\NoCSRFRequired; use OCP\AppFramework\Http\JSONResponse; use OCP\IRequest; use OCP\IUserSession; use OCP\IDBConnection;
class AlbumController extends Controller {
 public function __construct(IRequest $r, private IUserSession $session, private IDBConnection $db, private ?AlbumSyncOrchestrator $orchestrator=null){parent::__construct(Application::APP_ID,$r);}
 #[NoAdminRequired]
 #[NoCSRFRequired]
 public function sync(): JSONResponse {
  $u=$this->session->getUser(); if(!$u||!str_starts_with(strtolower($this->request->getHeader('Authorization')),'basic ')) return new JSONResponse(['error'=>'Authentication required'],401);
  $p=$this->request->getParams(); $sid=$p['sourceId']??null; if(!is_string($sid)||!$this->orchestrator) return new JSONResponse(['error'=>'Invalid album sync request'],400);
  try { $r=$this->orchestrator->sync(strtolower($sid),$u->getUID()); return new JSONResponse(['status'=>$r['errors']?'partial':'completed','summary'=>['albumsSeen'=>$r['albums_seen'],'albumsCreated'=>$r['albums_created'],'albumsReused'=>$r['albums_reused'],'foldersSkipped'=>$r['folders_skipped'],'membershipsSeen'=>$r['memberships_seen'],'membershipsCreated'=>$r['memberships_created'],'membershipsReused'=>$r['memberships_reused'],'membershipsSkippedNotImported'=>$r['memberships_skipped_not_imported'],'errors'=>$r['errors']]]); }
  catch(\InvalidArgumentException $e){return new JSONResponse(['error'=>$e->getMessage()],400);} catch(\Throwable $e){return new JSONResponse(['error'=>'Album sync failed'],500);}
 }
 #[NoAdminRequired]
 #[NoCSRFRequired]
 public function inventory(): JSONResponse {
  $u=$this->session->getUser(); if(!$u||!str_starts_with(strtolower($this->request->getHeader('Authorization')),'basic ')) return new JSONResponse(['error'=>'Authentication required'],401);
  $p=$this->request->getParams(); $s=$p['source']??null; $as=$p['albums']??null; if(!is_array($s)||!is_string($s['sourceId']??null)||!is_string($s['name']??null)||!is_array($as)||!array_is_list($as)) return new JSONResponse(['error'=>'Invalid album inventory'],400);
  $uid=$u->getUID(); $sid=strtolower($s['sourceId']); $now=(new \DateTimeImmutable('now',new \DateTimeZone('UTC')))->format('Y-m-d\\TH:i:s.u\\Z'); $this->db->beginTransaction();
  try { $q=$this->db->getQueryBuilder(); $q->select('id')->from('apc_sources')->where($q->expr()->eq('user_id',$q->createNamedParameter($uid)),$q->expr()->eq('source_id',$q->createNamedParameter($sid))); if(!$q->executeQuery()->fetch()) throw new \InvalidArgumentException('Source must be registered first'); $ids=[];
   foreach($as as $a){if(!is_array($a)||!is_string($a['localIdentifier']??null)||!is_string($a['name']??null)||!in_array($a['kind']??null,['album','folder'],true)) throw new \InvalidArgumentException('Invalid album kind'); $q=$this->db->getQueryBuilder(); $q->select('id')->from('apc_source_albums')->where($q->expr()->eq('user_id',$q->createNamedParameter($uid)),$q->expr()->eq('source_id',$q->createNamedParameter($sid)),$q->expr()->eq('local_identifier',$q->createNamedParameter($a['localIdentifier']))); $row=$q->executeQuery()->fetch(); if($row){$id=(int)$row['id']; $q=$this->db->getQueryBuilder(); $q->update('apc_source_albums')->set('name',$q->createNamedParameter($a['name']))->set('cloud_identifier',$q->createNamedParameter($a['cloudIdentifier']??null))->set('parent_local_identifier',$q->createNamedParameter($a['parentLocalIdentifier']??null))->set('kind',$q->createNamedParameter($a['kind']))->set('last_seen_at',$q->createNamedParameter($now))->where($q->expr()->eq('id',$q->createNamedParameter($id))); $q->executeStatement();} else {$q=$this->db->getQueryBuilder(); $q->insert('apc_source_albums')->values(['user_id'=>$q->createNamedParameter($uid),'source_id'=>$q->createNamedParameter($sid),'local_identifier'=>$q->createNamedParameter($a['localIdentifier']),'cloud_identifier'=>$q->createNamedParameter($a['cloudIdentifier']??null),'name'=>$q->createNamedParameter($a['name']),'parent_local_identifier'=>$q->createNamedParameter($a['parentLocalIdentifier']??null),'kind'=>$q->createNamedParameter($a['kind']),'created_at'=>$q->createNamedParameter($now),'last_seen_at'=>$q->createNamedParameter($now)])->executeStatement(); $id=(int)$this->db->lastInsertId('apc_source_albums');} $ids[]=$id; }
   foreach($as as $i=>$a) foreach(($a['assets']??$a['assetIdentities']??[]) as $ident){if(!is_string($ident)) throw new \InvalidArgumentException('Invalid asset identity'); $q=$this->db->getQueryBuilder(); $q->select('id','source_id','user_id')->from('apc_assets')->where($q->expr()->orX($q->expr()->eq('local_identifier',$q->createNamedParameter($ident)),$q->expr()->eq('cloud_identifier',$q->createNamedParameter($ident)))); $rows=$q->executeQuery()->fetchAllAssociative(); if(!$rows) throw new \InvalidArgumentException('Asset not found'); $ar=$rows[0]; if($ar['user_id']!==$uid||$ar['source_id']!==$sid) throw new \InvalidArgumentException('Cross-source or cross-user membership'); $q=$this->db->getQueryBuilder(); $q->select('id')->from('apc_album_memberships')->where($q->expr()->eq('user_id',$q->createNamedParameter($uid)),$q->expr()->eq('source_id',$q->createNamedParameter($sid)),$q->expr()->eq('album_id',$q->createNamedParameter($ids[$i])),$q->expr()->eq('asset_id',$q->createNamedParameter((int)$ar['id']))); if($q->executeQuery()->fetch()) continue; $q=$this->db->getQueryBuilder(); $q->insert('apc_album_memberships')->values(['user_id'=>$q->createNamedParameter($uid),'source_id'=>$q->createNamedParameter($sid),'album_id'=>$q->createNamedParameter($ids[$i]),'asset_id'=>$q->createNamedParameter((int)$ar['id']),'first_seen_at'=>$q->createNamedParameter($now),'last_seen_at'=>$q->createNamedParameter($now)])->executeStatement(); }
   $this->db->commit(); return new JSONResponse(['albums'=>$ids,'count'=>count($ids)]);
  } catch(\Throwable $e){if($this->db->inTransaction()) $this->db->rollBack(); return new JSONResponse(['error'=>$e->getMessage()],400);}
 }
}
